merges qt4 branches back to trunk
git-svn-id: http://svn.mythtv.org/svn/trunk@16790 7dbf422c-18fa-0310-86e9-fd20926502f2

diff --git a/mythplugins/configure b/mythplugins/configure
--- a/mythplugins/configure
+++ b/mythplugins/configure
@@ -25,6 +25,7 @@ zoneminder="yes"
 movies="yes"
 
 cc="gcc"
+qmake="qmake"
 
 opengl="yes"
 visual="yes"
@@ -57,8 +58,9 @@ Options: [defaults in brackets after descriptions]
 NB:      all --enable-* options can be reversed with --disable-*
 
 Generic options:
-  --prefix=PREFIX          MythTV install location PREFIX [$prefix]"
-  --libdir-name=LIBNAME    install/look for libs in PREFIX/LIBNAME [$libdir_name]"
+  --prefix=PREFIX          MythTV install location PREFIX [$prefix]
+  --qmake=QMAKE            use specified qmake [$qmake]
+  --libdir-name=LIBNAME    install/look for libs in PREFIX/LIBNAME [$libdir_name]
   --help                   print this message
   --enable-all             Enable all options
   --enable-opengl          enable OpenGL (Music and Gallery) [$opengl]
@@ -69,8 +71,8 @@ MythArchive related options:
   --enable-create-dvd      enable dvd creation [$createdvd]
   --enable-create-archive  enable native archive creation [$createarchive]
 
-MythBrowser related options:
-  --enable-mythbrowser     build the mythbrowser plugin [$browser]
+#MythBrowser related options:
+#  --enable-mythbrowser     build the mythbrowser plugin [$browser]
 
 MythControls related options:
   --enable-mythcontrols    build the mythcontrols plugin [$controls]
@@ -151,6 +153,8 @@ for opt do
   case "$opt" in
   --prefix=*) prefix=`echo $opt | cut -d '=' -f 2`
   ;;
+  --qmake=*) qmake=`echo $opt | cut -d '=' -f 2`
+  ;;
   --libdir-name=*) libdir_name=`echo $opt | cut -d '=' -f 2`;
   ;;
   --enable-mytharchive) archive="yes"
@@ -197,10 +201,12 @@ for opt do
   ;;
   --disable-mythphone) phone="no"
   ;;
-  --enable-mythbrowser) browser="yes"
-  ;;
-  --disable-mythbrowser) browser="no"
-  ;;
+#  --enable-mythbrowser) 
+#      echo "mythbrowser won't build with qt4 until it is ported to kde4 or QtWebKit"
+#      #browser="yes"
+#  ;;
+#  --disable-mythbrowser) browser="no"
+#  ;;
   --enable-mythzoneminder) zoneminder="yes"
   ;;
   --disable-mythzoneminder) zoneminder="no"
@@ -362,6 +368,20 @@ has_header()
     done
     expr $HAS_IT : "yes" > /dev/null
 }
+
+is_qmake4()
+{
+    $1 --version 2>&1 | grep -q "Qt version 4"
+}
+ 
+if ! is_qmake4 $qmake; then
+    if is_qmake4 qmake-qt4; then
+        qmake=qmake-qt4
+    else
+        echo "qmake for Qt4 not found. Please specify the correct qmake with --qmake="
+        exit 1
+    fi
+fi
 
 if test "$opengl" != "no" ; then
     opengl="no"
@@ -533,24 +553,6 @@ if test "$zoneminder" != "no" ; then
     fi
 fi
 
-if test "$browser" != "no" ; then
-    hasit="no"
-    if has_library libkhtml ; then
-        if has_header kde/khtml_part.h                  || \
-           has_header /opt/kde3/include/khtml_part.h    || \
-           has_header /usr/kde/3.3/include/khtml_part.h || \
-           has_header /usr/kde/3.4/include/khtml_part.h || \
-           has_header /usr/kde/3.5/include/khtml_part.h || \
-           has_header khtml_part.h ; then
-            hasit="yes"
-        fi
-    fi
-    if test "$hasit" = "no" ; then
-        echo "Disabling MythBrowser due to missing KDE development packages."
-        browser="no"
-    fi
-fi
-
 if test "$festival" != "no" ; then
     festival="no"
     if has_library libFestival && has_library libestools && has_library libestbase && has_library libeststring && has_library libtermcap && has_header festival/festival.h ; then
@@ -603,6 +605,8 @@ fi
 echo ""
 echo "Configuration settings: "
 echo " "
+echo "        qmake          $(which $qmake)"
+echo " "
 
 echo "#" > ./config.pro
 echo "#    Automatically generated by mythplugin configure" >> ./config.pro
@@ -616,12 +620,12 @@ else
   echo "        MythArchive    plugin will not be built"
 fi
 
-if test "$browser" = "yes" ; then
-  echo "        MythBrowser    plugin will be built"
-  echo "SUBDIRS += mythbrowser" >> ./config.pro
-else
-  echo "        MythBrowser    plugin will not be built"
-fi
+#if test "$browser" = "yes" ; then
+#  echo "        MythBrowser    plugin will be built"
+#  echo "SUBDIRS += mythbrowser" >> ./config.pro
+#else
+#  echo "        MythBrowser    plugin will not be built"
+#fi
 
 if test "$controls" = "yes" ; then
   echo "        MythControls   plugin will be built"
@@ -990,8 +994,4 @@ echo "SUBDIRS += cleanup " >> ./config.pro
 
 echo ""
 
-if test -x $QTDIR/bin/qmake; then
-  $QTDIR/bin/qmake QMAKE=${QTDIR}/bin/qmake mythplugins.pro
-else
-  qmake mythplugins.pro
-fi
+${qmake} QMAKE=$(which ${qmake}) mythplugins.pro
diff --git a/mythtv/configure b/mythtv/configure
--- a/mythtv/configure
+++ b/mythtv/configure
@@ -115,6 +115,7 @@ BLOCK_QUOTE
   echo "  --cc=CC                  use C compiler CC [$cc]"
   echo "  --make=MAKE              use specified make [$make]"
 BLOCK_QUOTE
+  echo "  --qmake=QMAKE            use specified qmake [$qmake]"
   echo "  --extra-cflags=ECFLAGS   add ECFLAGS to CFLAGS [$CFLAGS]"
   echo "  --extra-cxxflags=ECXFLAGS add ECXXFLAGS to list of flags for C++ compile"
   echo "  --extra-ldflags=ELDFLAGS add ELDFLAGS to LDFLAGS [$LDFLAGS]"
@@ -1098,6 +1099,7 @@ distcc="yes"
 ar="ar"
 ranlib="ranlib"
 make="make"
+qmake="qmake"
 strip="strip"
 asmalign_pot="unknown"
 ln_s="ln -sf"
@@ -1320,6 +1322,8 @@ for opt do
   --cc=*) cc="$optval"
   ;;
   --make=*) make="$optval"
+  ;;
+  --qmake=*) qmake="$optval"
   ;;
   --extra-cflags=*) check_ecflags "$optval"
   ;;
@@ -1938,6 +1942,14 @@ gnu_make(){
 
 if ! gnu_make $make; then
     gnu_make gmake && make=gmake || die "GNU make not found."
+fi
+
+is_qmake4(){
+    $1 --version 2>&1 | grep -q "Qt version 4"
+}
+
+if ! is_qmake4 $qmake; then
+    is_qmake4 qmake-qt4 && qmake=qmake-qt4 || die "qmake for Qt4 not found. Please specify the correct qmake with --qmake="
 fi
 
 # make sure we can execute files in $TMPDIR
@@ -2659,9 +2671,6 @@ fi
 enabled freetype2 ||
     die "ERROR! You must have FreeType installed to compile MythTV."
 
-has_library libqt-mt ||
-    die "ERROR! You must have a threaded Qt installed to compile MythTV."
-
 #has_library libmysqlclient || has_library mysql/libmysqlclient ||
 #    die "ERROR! You must have a MySQL library installed to run MythTV."
 #
@@ -2860,6 +2869,7 @@ if test x"$compile_type" = x"debug" -a $arch = "x86_32" -a \
 fi
 echo "Compiler cache            $ccache$ccache_txt"
 echo "DistCC                    $distcc$distcc_txt"
+echo "qmake                     $(which $qmake)"
 echo "install prefix            $PREFIX"
 <<BLOCK_QUOTE
 echo "source path               $source_path"
@@ -3451,9 +3461,6 @@ END
 
 rm -f $TMPO $TMPC $TMPE $TMPS $TMPH
 
-if test -x $QTDIR/bin/qmake; then
-  $QTDIR/bin/qmake QMAKE=${QTDIR}/bin/qmake mythtv.pro
-else
-  qmake mythtv.pro
-fi
+
+$qmake QMAKE=$(which $qmake) mythtv.pro
 
