Added checks in mythplugins configure for the perl modules used by the scrapers in mythweather.  For now, if ANY of them are missing, all of mythweather is disabled.  We really need more granularity here.  I'll have to think that through.
git-svn-id: http://svn.mythtv.org/svn/trunk@25141 7dbf422c-18fa-0310-86e9-fd20926502f2

diff --git a/mythplugins/configure b/mythplugins/configure
--- a/mythplugins/configure
+++ b/mythplugins/configure
@@ -433,6 +433,24 @@ if ! disabled netvision; then
     disabled netvision && echo "Disabling MythNetvision due to missing dependencies."
 fi
 
+if ! disabled weather; then
+    check_pl_lib(){
+        log check_pl_lib "$@"
+        check_cmd perl -e "use ${1};"
+    }
+
+    disable_weather(){
+        echo "WARNING: disabling MythWeather; missing $1"
+        disable weather
+    }
+
+    check_pl_lib "Date::Manip"  || disable_weather "Date::Manip"
+    check_pl_lib "XML::Simple"  || disable_weather "XML::Simple"
+    check_pl_lib "Image::Size"  || disable_weather "Image::Size"
+    check_pl_lib "DateTime::Format::ISO8601" || 
+        disable_weather "DateTime::Format::ISO8601"
+    check_pl_lib "SOAP::Lite"  || disable_weather "SOAP::Lite"
+fi
 
 if test "$music" != "no" ; then
     vorbis="no"
