Modify plugin configure to check python dependencies for MythNetvision.  Could probably do with a port of the command line switches to specify a python binary from the core configure, but this should work for now.
git-svn-id: http://svn.mythtv.org/svn/trunk@24575 7dbf422c-18fa-0310-86e9-fd20926502f2

diff --git a/mythplugins/configure b/mythplugins/configure
--- a/mythplugins/configure
+++ b/mythplugins/configure
@@ -319,6 +319,17 @@ is_qmake4()
     $1 --version 2>&1 | grep -q "Qt version 4"
 }
 
+check_py_lib(){
+    python <<EOF
+import sys
+try:
+    import ${1}
+except:
+    sys.exit(1)
+sys.exit(0)
+EOF
+}
+
 if ! is_qmake4 $qmake; then
     if is_qmake4 qmake-qt4; then
         qmake=qmake-qt4
@@ -384,6 +395,70 @@ if test "$exif" != "no" ; then
         fi
     fi
 fi
+
+if test "$netvision" != "no" ; then
+    mythbindings="no"
+    check_py_lib MythTV
+    if test $? != 1 ; then
+        mythbindings="yes"
+    else
+        echo "MythNetvision requires that the MythTV Python bindings be installed and properly configured."
+    fi
+
+    pcurl="no"
+    check_py_lib pycurl
+    if test $? != 1 ; then
+        pcurl="yes"
+    else
+        echo "MythNetvision requires the Python pycurl library (pycurl) installed."
+    fi
+
+    plxml="no"
+    check_py_lib lxml
+    if test $? != 1 ; then
+        plxml="yes"
+    else
+        echo "MythNetvision requires the Python lxml library (lxml) installed."
+    fi
+
+    pxml="no"
+    check_py_lib xml
+    if test $? != 1 ; then
+        pxml="yes"
+    else
+        echo "MythNetvision requires the Python XML library (xml) installed."
+    fi
+
+    purl="no"
+    check_py_lib urllib
+    if test $? != 1 ; then
+        purl="yes"
+    else
+        echo "MythNetvision requires the Python URL library (urllib) installed."
+    fi
+
+    purl2="no"
+    check_py_lib urllib2
+    if test $? != 1 ; then
+        purl2="yes"
+    else
+        echo "MythNetvision requires the Python URL library 2 (urllib2) installed."
+    fi
+
+    poauth="no"
+    check_py_lib oauth
+    if test $? != 1 ; then
+        poauth="yes"
+    else
+        echo "MythNetvision requires the Python OAuth library (oauth) installed."
+    fi
+
+    if test "$mythbindings" = "no" -o "$pcurl" = "no" -o "$plxml" = "no" -o "$pxml" = "no" -o "$purl" = "no" -o "$purl2" = "no" -o "$poauth" = "no"; then
+        echo "Disabling MythNetvision due to missing dependencies."
+        netvision="no"
+    fi
+fi
+
 
 if test "$music" != "no" ; then
     vorbis="no"
