closes #42
Unfortunately, everyone will need to run configure for this.

This includes Mask Spieth's distclean patch and a small fix 
from Sage at gypsycaravan.com for MythTV to compile with Qt Embedded.

This requires a change in the edit, compile, run cycle. Whenever
you typed "make distclean" before, you now type "make clean" instead.
"make distclean" will really do a distribution ready clean, forcing 
you to re-run configure...



git-svn-id: http://svn.mythtv.org/svn/trunk@6829 7dbf422c-18fa-0310-86e9-fd20926502f2

diff --git a/mythtv/configure b/mythtv/configure
--- a/mythtv/configure
+++ b/mythtv/configure
@@ -2612,9 +2612,11 @@ diff $TMPH $MYTH_CONFIG_H >/dev/null 2>&1
 if test $? -ne 0 ; then
   mv -f $TMPH $MYTH_CONFIG_H
   rm -f config.h
-  ln -s $MYTH_CONFIG_H config.h
 else
   echo "$MYTH_CONFIG_H is unchanged"
+fi
+if ! test -L config.h ; then
+  ln -s $MYTH_CONFIG_H config.h
 fi
 
 if [ ! -e config.h ] ; then
@@ -2623,6 +2625,30 @@ fi
 
 rm -f config.mak
 ln -s $MYTH_CONFIG_MAK config.mak
+
+# Create a special cleanup makefile that will allow make clean to work
+if [ ! -e config ] ; then
+  mkdir config
+fi
+cat - > config/Makefile <<END
+
+all:	
+qmake_all:
+
+clean:
+	-rm -f ../*/*/*.so*
+	-rm -f ../*/*/*.a
+
+install:
+uninstall:
+
+distclean: clean
+	-rm -f ../$MYTH_CONFIG_MAK
+	-rm -f ../$MYTH_CONFIG_H
+	-rm -f ../config.mak ../config.h
+	-rm -f ../Makefile
+
+END
 
 rm -f $TMPO $TMPC $TMPE $TMPS $TMPH
 
