Enable symbol visibility by default
This should reduce the frequency of broken builds by those developers
who don't currently enable this option.

Enabling symbol visibility hides symbols by default and only makes
public those symbols which are needed in public APIs. This substantially
reduces the binary size of libraries and makes them marginally faster
too. For more information see the GCC documentation -
http://gcc.gnu.org/wiki/Visibility

A distclean is required.

diff --git a/mythtv/configure b/mythtv/configure
--- a/mythtv/configure
+++ b/mythtv/configure
@@ -82,7 +82,7 @@ Advanced options (experts only):
   --extra-cflags=ECFLAGS   add ECFLAGS to CFLAGS [$CFLAGS]
   --extra-cxxflags=ECXFLAGS add ECXXFLAGS to list of flags for C++ compile
   --extra-ldflags=ELDFLAGS add ELDFLAGS to LDFLAGS [$LDFLAGS]
-  --enable-symbol-visibility enables symbol visibility options
+  --disable-symbol-visibility disables symbol visibility options
   --arch=ARCH              select architecture [$arch]
   --tune=CPU               tune instruction usage for a particular CPU [$tune]
   --cpu=CPU                select the minimum required CPU (affects
@@ -1932,6 +1932,7 @@ enable opengl
 enable opengl_vsync
 enable opengl_video
 enable quartz_video
+enable symbol_visibility
 enable v4l
 enable x11
 enable xrandr
@@ -3254,10 +3255,10 @@ if ! is_qmake4 $qmake; then
     is_qmake4 qmake-qt4 && qmake=qmake-qt4 || die "qmake for Qt4.5 or newer not found.\nPlease specify the correct qmake with --qmake="
 fi
 
-if ! expr $($qmake -query QT_VERSION) : "4\.[5-9]\.[0-9]" >/dev/null; then 
-    die "Qt4.5 or newer is required to build MythTV." 
-fi 
-    
+if ! expr $($qmake -query QT_VERSION) : "4\.[5-9]\.[0-9]" >/dev/null; then
+    die "Qt4.5 or newer is required to build MythTV."
+fi
+
 enable_pic() {
     enable pic
     add_cppflags -DPIC
@@ -3588,7 +3589,7 @@ fi
 disabled  zlib || check_lib   zlib.h      zlibVersion -lz   || disable  zlib
 disabled bzlib || check_lib2 bzlib.h BZ2_bzlibVersion -lbz2 || disable bzlib
 
-# Attempt to use libudev for mediamonitor 
+# Attempt to use libudev for mediamonitor
 enabled libudev && check_lib2 libudev.h udev_new -ludev || disable libudev
 
 enabled ffmpeg_pthreads && enable pthreads
@@ -4152,7 +4153,7 @@ fi
 # Check for perl dependencies
 # Modules distributed in Perl core
 if enabled bindings_perl; then
-    check_pl_lib "ExtUtils::MakeMaker" || 
+    check_pl_lib "ExtUtils::MakeMaker" ||
         disable_bindings_perl "ExtUtils::MakeMaker"
     check_pl_lib Config           || disable_bindings_perl Config
     check_pl_lib Exporter         || disable_bindings_perl Exporter
@@ -4163,9 +4164,9 @@ if enabled bindings_perl; then
     check_pl_lib DBI              || disable_bindings_perl DBI
     check_pl_lib "HTTP::Request"  || disable_bindings_perl "HTTP::Request"
     check_pl_lib "LWP::UserAgent" || disable_bindings_perl "LWP::UserAgent"
-    check_pl_lib "Net::UPnP::QueryResponse" || 
+    check_pl_lib "Net::UPnP::QueryResponse" ||
         disable_bindings_perl "Net::UPnP::QueryResponse"
-    check_pl_lib "Net::UPnP::ControlPoint"  || 
+    check_pl_lib "Net::UPnP::ControlPoint"  ||
         disable_bindings_perl "Net::UPnP::ControlPoint"
 fi
 
