Make configure's qmake check look for Qt4.4+ to prevent people from mistakenly installing older versions and having to reinstall Qt4.4+. Also made the qmake error message specify "qmake for Qt4.4 or newer" rather than "qmake for Qt4"
git-svn-id: http://svn.mythtv.org/svn/trunk@23618 7dbf422c-18fa-0310-86e9-fd20926502f2

diff --git a/mythtv/configure b/mythtv/configure
--- a/mythtv/configure
+++ b/mythtv/configure
@@ -3111,11 +3111,11 @@ check_optflags -fomit-frame-pointer
 
 
 is_qmake4(){
-    $1 --version 2>&1 | grep -q "Qt version 4"
+    $1 --version 2>&1 | egrep -q -e "Qt version 4\.[4-9]\.[0-9]"
 }
 
 if ! is_qmake4 $qmake; then
-    is_qmake4 qmake-qt4 && qmake=qmake-qt4 || die "qmake for Qt4 not found. Please specify the correct qmake with --qmake="
+    is_qmake4 qmake-qt4 && qmake=qmake-qt4 || die "qmake for Qt4.4 or newer not found.\nPlease specify the correct qmake with --qmake="
 fi
 
 if ! expr $($qmake -query QT_VERSION) : "4\.[4-9]\.[0-9]" >/dev/null; then 
