Use the system provided libbluray (when >= 0.9.3).
The copy of libbluray embedded into MythTV was recently updated and is
now current, but it would be better to use the system provided
libbluray where possible.  MythTV apparently requires a minimum
version of 0.9.3, so only use the system libbluray if its a later
version.  Eventually once all the distributions with old versions of
libbluray become unsupported, the embedded copy of libbluray can be
removed from the MythTV sources.

diff --git a/mythtv/configure b/mythtv/configure
--- a/mythtv/configure
+++ b/mythtv/configure
@@ -1383,7 +1383,6 @@ EXTERNAL_LIBRARY_LIST="
     $EXTERNAL_LIBRARY_GPLV3_LIST
     jni
     libass
-    libbluray
     libfontconfig
     libfreetype
     libiec61883
@@ -1985,6 +1984,7 @@ MYTHTV_CONFIG_LIST='
     x11
     xnvctrl
     xnvctrl_external
+    libbluray_external
     xrandr
     xv
     profiletype
@@ -2787,6 +2787,7 @@ disable mythlogserver
 enable exiv2
 enable systemd_notify
 enable systemd_journal
+enable libbluray_external
 
 # mythtv paths
 dvb_path_default="${sysinclude:-$sysroot/usr/include}"
@@ -5618,7 +5619,7 @@ check_exec -lm << EOF && enable cpu_clips_negative
         return 0 ;
     }
 EOF
-require_pkg_config samplerate samplerate samplerate.h src_get_version
+require_pkg_config samplerate samplerate samplerate.h src_get_version -lm
 
 # required to compile inline sse with some compilers
 enabled x86 && enabled sse2 && add_cxxflags "-msse"
@@ -5915,7 +5916,52 @@ fi
 # Attempt to use libudev for mediamonitor
 enabled libudev && check_lib udev libudev.h udev_new  || disable libudev
 
-# libmythbluray
+# libmythbluray!
+if enabled libbluray_external; then
+    if $(pkg-config --atleast-version="0.9.3" libbluray); then
+        use_pkg_config libbluray libbluray libbluray/bluray.h bd_open
+    else
+        case $target_os in
+            linux)
+                # Some older supported linux versions don't have a
+                # libbluray current enough to support MythTV.  Allow
+                # only those systems to reach the bottom of the
+                # following case statement.  This list should only
+                # shrink over time.
+                . /etc/os-release
+                case $ID in
+                    centos)
+                        if test $VERSION_ID -gt 7; then
+                            die "ERROR: can not find libbluray."
+                        fi
+                        ;;
+                    ubuntu)
+                        case $VERSION_ID in
+                            17*|18*|19*|2*)
+                                die "ERROR: can not find libbluray."
+                                ;;
+                        esac
+                        ;;
+                    debian)
+                        if test $VERSION_ID -gt 8; then
+                            die "ERROR: can not find libbluray."
+                        fi
+                        ;;
+                    *)
+                        die "ERROR: can not find libbluray."
+                        ;;
+                esac
+                disable libbluray_external
+                ;;
+            *)
+                # FreeBSD provides libbluray 1.0.2
+                # All others unknown.
+                die "ERROR: can not find libbluray."
+                ;;
+        esac
+    fi
+fi
+
 antbin=""
 if enabled bdjava; then
     enabled x86_64 && java_arch=amd64
@@ -5962,7 +6008,6 @@ done
 # these are off by default, so fail if requested and not available
 enabled jni               && { [ $target_os = "android" ] && check_header jni.h && enabled pthreads || die "ERROR: jni not found"; }
 enabled libiec61883       && require libiec61883 libiec61883/iec61883.h iec61883_cmp_connect -lraw1394 -lavc1394 -lrom1394 -liec61883
-enabled libbluray         && require_pkg_config libbluray libbluray libbluray/bluray.h bd_open -lbluray
 enabled fontconfig        && enable libfontconfig
 enabled libfontconfig     && require_pkg_config libfontconfig fontconfig "fontconfig/fontconfig.h" FcInit
 enabled libfreetype       && require_pkg_config libfreetype2 freetype2 "ft2build.h FT_FREETYPE_H" FT_Init_FreeType
@@ -7236,6 +7281,11 @@ fi
 echo "libdns_sd (Bonjour)       ${libdns_sd-no}"
 echo "libcrypto                 ${libcrypto-no}"
 echo "OpenGL ES 2.0             ${opengles-no}"
+if enabled libbluray_external; then
+    echo "bluray support            yes (system)"
+else
+    echo "bluray support            yes (internal)"
+fi
 echo "BD-J (Bluray java)        ${bdjava-no}"
 echo "BD-J type                 ${bdj_type}"
 echo "systemd_notify            ${systemd_notify-no}"
@@ -7721,9 +7771,11 @@ if enabled mythlogserver; then
     (cd external/nzmqt/src ; \
            ${qmakeconf} -o Makefile)
 fi
-echo "Configuring libmythbluray..."
-(cd external/libmythbluray ; \
-       ${qmakeconf} -o Makefile)
+if ! enabled libbluray_external; then
+    echo "Configuring libmythbluray..."
+    (cd external/libmythbluray ; \
+           ${qmakeconf} -o Makefile)
+fi
 echo "Configuring libmythdvdnav..."
 (cd external/libmythdvdnav ; \
        ${qmakeconf} -o Makefile)
