remove QtWebkit

diff --git a/mythtv/configure b/mythtv/configure
--- a/mythtv/configure
+++ b/mythtv/configure
@@ -6371,16 +6371,16 @@ else
     qt_libs="-L${sysroot}/$(${qmake} -query QT_INSTALL_LIBS)"
 fi
 
-if $(pkg-config --exists Qt5WebKit) || $(pkg-config --exists QtWebKit) ; then
-    enable qtwebkit
-else
-    check_ecxx ${qt_inc} ${qt_inc}/QtCore <<EOF && enable qtwebkit
-#include <QtWebKit/QtWebKit>
-int main(void){ return 0; }
-EOF
-fi
+# if $(pkg-config --exists Qt5WebKit) || $(pkg-config --exists QtWebKit) ; then
+#     enable qtwebkit
+# else
+#     check_ecxx ${qt_inc} ${qt_inc}/QtCore <<EOF && enable qtwebkit
+# #include <QtWebKit/QtWebKit>
+# int main(void){ return 0; }
+# EOF
+# fi
 
-enabled qtwebkit || die "Error! QtWebkit headers not found"
+# enabled qtwebkit || die "Error! QtWebkit headers not found"
 
 if $(pkg-config --exists Qt5Script) || $(pkg-config --exists QtScript) ; then
     enable qtscript
