Initial support for replacing QWebKit with QWebEngine
Very lightly tested on Qt 5.15.17 and 6.6.2 and only using MythBrowser which
is the primary reason for it anyway. It's not yet completely equivalent to
the original some features like download support and the browser API are
missing.

There is a bug in MythUI when using Qt6 and running MythTV in a window any
scaling factor is not applied properly to the GUI but is to the window size.

Don't know what needs to be done for cmake so that will probably be broken.

diff --git a/mythtv/configure b/mythtv/configure
--- a/mythtv/configure
+++ b/mythtv/configure
@@ -1736,7 +1736,7 @@ MYTHTV_CONFIG_LIST='
     mmal
     opengl
     egl
-    qtwebkit
+    qtwebengine
     qtscript
     qtdbus
     sqlite3
@@ -2212,8 +2212,6 @@ enable system_libexiv2
 enable system_libbluray
 enable system_libudfread
 enable waylandextras
-# Enable by default so that we can explicitly disable using --disable-qtwebkit
-enable qtwebkit
 enable qtscript
 
 # mythtv paths
@@ -5826,21 +5824,21 @@ case $target_os in
 esac
 
 # Omit Qt5 modules that aren't in Qt6.
-# qtwebkit and qtscript are enabled by default.
-# if either is disabled om the command line we will
+# qtscript is enabled by default.
+# if it is disabled on the command line we will
 # not enable it here.
-if [ $qt_version -lt $(version2num "6.0.0") ]; then
-    if enabled qtwebkit ; then
-        if ! pkg-config --exists Qt5WebKit && ! pkg-config --exists QtWebKit ; then
-            check_ecxx ${qt_inc} ${qt_inc}/QtCore <<EOF || disable qtwebkit
-#include <QtWebKit/QtWebKit>
+if $(pkg-config --exists Qt5WebEngine) || $(pkg-config --exists QtWebEngine) ; then
+    enable qtwebengine
+else
+    check_ecxx ${qt_inc} ${qt_inc}/QtCore <<EOF && enable qtwebengine
+#include <QtWebEngine/QtWebEngine>
 int main(void){ return 0; }
 EOF
-        fi
-    fi
+fi
 
-    enabled qtwebkit || warn "QtWebkit disabled."
+enabled qtwebengine || warn "QtWebEngine headers not found. Plugins may fail."
 
+if [ $qt_version -lt $(version2num "6.0.0") ]; then
     if enabled qtscript ; then
         if ! pkg-config --exists Qt5Script && ! pkg-config --exists QtScript ; then
             check_ecxx ${qt_inc} <<EOF || disable qtscript
@@ -5853,7 +5851,6 @@ EOF
     enabled qtscript || warn "QtScript disabled."
 else
     # Disable for QT6 and above
-    disable qtwebkit
     disable qtscript
 fi
 
