Work around missing pkg-config in QtWebKit test. Mainly for Mac OS X
git-svn-id: http://svn.mythtv.org/svn/trunk@20468 7dbf422c-18fa-0310-86e9-fd20926502f2

diff --git a/mythtv/configure b/mythtv/configure
--- a/mythtv/configure
+++ b/mythtv/configure
@@ -2961,8 +2961,16 @@ enabled lamemp3 && check_lib2 lame/lame.h lame_init -lmp3lame -lm ||
 if $(pkg-config --atleast-version 4.4.0 QtWebKit) ; then
     enable qtwebkit
 else
-    disable qtwebkit && echo "Warning! QtWebkit headers not found, MythBrowser will not work."
+    # For environments that don't have pkg-config:
+    check_cpp <<EOF && enable qtwebkit
+#include <QtWebKit/QtWebKit>
+#if QT_VERSION < 0x040400
+die
+#endif
+EOF
 fi
+
+enabled qtwebkit || echo "Warning! QtWebkit headers not found, MythBrowser will not work."
 
 if enabled firewire; then
     firewire="no"
