Check for QtScript support in configure.
Some systems (at least Mac OS X) have separated QtScript into its own
package, so check for it in configure so the user doesn't waste time
compiling without it.

diff --git a/mythtv/configure b/mythtv/configure
--- a/mythtv/configure
+++ b/mythtv/configure
@@ -1355,6 +1355,7 @@ MYTHTV_CONFIG_LIST='
     opengl_video
     qtdbus
     qtwebkit
+    qtscript
     quartz_video
     v4l2
     v4l1
@@ -4046,6 +4047,20 @@ EOF
 fi
 
 enabled qtwebkit || die "Error! QtWebkit headers not found"
+
+if $(pkg-config --exists QtScript) ; then
+    enable qtscript
+else
+    check_ld_cxx ${qt_inc} ${qt_inc}/QtScript ${qt_libs} -lQtScript <<EOF && enable qtscript
+#include <QtScript/QtScript>
+int main(void){
+    QScriptEngine myEngine;
+    return myEngine.evaluate("0").toNumber();
+}
+EOF
+fi
+
+enabled qtscript || die "Error! QtScript headers not found"
 
 # Check if Qt was built with DBus support:
 check_ld_cxx ${qt_inc} ${qt_inc}/QtDBus ${qt_libs} -lQtDBus <<EOF && enable qtdbus
