ffmpeg resync.  I really should cull out the codecs we have no use for. Fix Doug Larrick's channel changing bug. Tiny patch from Brett Lucey to not die if we give a null frame to the commercial detect stuff.
git-svn-id: http://svn.mythtv.org/svn/trunk@2434 7dbf422c-18fa-0310-86e9-fd20926502f2

diff --git a/mythtv/configure b/mythtv/configure
--- a/mythtv/configure
+++ b/mythtv/configure
@@ -2,6 +2,68 @@
 #
 # ffmpeg configure script (c) 2000, 2001, 2002 Fabrice Bellard
 #
+
+if test x"$1" = x"-h" -o x"$1" = x"--help" ; then
+cat << EOF
+
+Usage: configure [options]
+Options: [defaults in brackets after descriptions]
+
+EOF
+echo "Standard options:"
+echo "  --help                   print this message"
+#echo "  --prefix=PREFIX          install in PREFIX [$prefix]"
+#echo "  --mandir=DIR             man documentation in DIR [PREFIX/man]"
+#echo "  --enable-mp3lame         enable mp3 encoding via libmp3lame [default=no]"
+#echo "  --enable-vorbis          enable vorbis support via libvorbisenc [default=no]"
+#echo "  --enable-faad            enable faad support via libfaad [default=no]"
+#echo "  --enable-faadbin         build faad support with runtime linking [default=no]"
+#echo "  --enable-faac            enable faac support via libfaac [default=no]"
+#echo "  --enable-mingw32         enable mingw32 native/cross windows compile"
+#echo "  --enable-a52             enable GPL'ed A52 support [default=no]"
+#echo "  --enable-a52bin          open liba52.so.0 at runtime [default=no]"
+#echo "  --enable-pp              enable GPL'ed post processing support [default=no]"
+#echo "  --enable-shared-pp       use libpostproc.so [default=no]"
+#echo "  --enable-shared          build shared libraries [default=no]"
+#echo "  --enable-amr_nb          enable amr_nb float audio codec"
+#echo "  --enable-amr_nb-fixed    use fixed point for amr-nb codec"
+#echo "  --enable-sunmlib         use Sun medialib [default=no]"
+#echo ""
+echo "Advanced options (experts only):"
+#echo "  --source-path=PATH       path of source code [$source_path]"
+#echo "  --cross-prefix=PREFIX    use PREFIX for compile tools [$cross_prefix]"
+#echo "  --cc=CC                  use C compiler CC [$cc]"
+#echo "  --make=MAKE              use specified make [$make]"
+echo "  --extra-cflags=ECFLAGS   add ECFLAGS to CFLAGS [$CFLAGS]"
+#echo "  --extra-ldflags=ELDFLAGS add ELDFLAGS to LDFLAGS [$LDFLAGS]"
+#echo "  --extra-libs=ELIBS       add ELIBS [$ELIBS]"
+#echo "  --cpu=CPU                force cpu to CPU  [$cpu]"
+#echo "  --tune=PROCESSOR         tune code for a particular CPU (may fails or misperforms on other CPUs)"
+#echo "  --powerpc-perf-enable    enable performance report on PPC (requires enabling PMC)"
+#echo "  --disable-mmx            disable mmx usage"
+#echo "  --disable-altivec        disable AltiVec usage"
+#echo "  --disable-audio-oss      disable OSS audio support [default=no]"
+#echo "  --disable-audio-beos     disable BeOS audio support [default=no]"
+#echo "  --disable-v4l            disable video4linux grabbing [default=no]"
+#echo "  --disable-dv1394         disable DV1394 grabbing [default=no]"
+#echo "  --disable-network        disable network support [default=no]"
+#echo "  --disable-zlib           disable zlib [default=no]"
+#echo "  --disable-simple_idct    disable simple IDCT routines [default=no]"
+#echo "  --disable-vhook          disable video hooking support"
+#echo "  --enable-gprof           enable profiling with gprof [$gprof]"
+#echo "  --disable-debug          disable debugging symbols"
+#echo "  --disable-opts           disable compiler optimizations"
+#echo "  --disable-mpegaudio-hp   faster (but less accurate)"
+#echo "                           mpegaudio decoding [default=no]"
+#echo "  --disable-ffserver       disable ffserver build"
+#echo "  --disable-ffplay         disable ffplay build"
+#echo "  --disable-risky          disables patent encumbered codecs"
+#echo "  --enable-small           optimize for size instead of speed"
+#echo ""
+#echo "NOTE: The object files are build at the place where configure is launched"
+exit 1
+fi
+
 # set temporary file name
 if test ! -z "$TMPDIR" ; then
     TMPDIR1="${TMPDIR}"
@@ -20,6 +82,7 @@ TMPH="${TMPDIR1}/ffmpeg-conf-${RANDOM}-$$-${RANDOM}.h"
 # default parameters
 prefix="/usr/local"
 mandir=""
+bindir=""
 cross_prefix=""
 cc="gcc"
 ar="ar"
@@ -70,6 +133,7 @@ mp3lame="no"
 vorbis="no"
 faad="no"
 faadbin="no"
+faac="no"
 a52="yes"
 a52bin="no"
 pp="yes"
@@ -98,8 +162,10 @@ LIBPREF="lib"
 LIBSUF=".a"
 SLIBPREF="lib"
 SLIBSUF=".so"
+EXESUF=""
 risky="yes"
 amr_nb="no"
+amr_wb="no"
 amr_nb_fixed="no"
 sunmlib="no"
 
@@ -172,30 +238,11 @@ darwin="yes"
 strip="strip -x"
 LDFLAGS="-d"
 FFSLDFLAGS=-Wl,-bind_at_load
-gcc_version="$($cc -v 2>&1 | grep version | cut -d ' ' -f3-)"
-case "$gcc_version" in
-*2.95*) 
-CFLAGS="-no-cpp-precomp -pipe -fomit-frame-pointer"
-;;
-*3.3*) 
-CFLAGS="-no-cpp-precomp -pipe -fomit-frame-pointer -mdynamic-no-pic -force_cpusubtype_ALL"
-;;
-*) 
-CFLAGS="-no-cpp-precomp -pipe -fomit-frame-pointer -mdynamic-no-pic"
-;;
-esac
 ;;
 MINGW32*)
-v4l="no"
-audio_oss="no"
-dv1394="no"
-ffserver="no"
-network="no"
+# Note: the rest of the mingw32 config is done afterwards as mingw32
+# can be forced on command line for linux cross compilation
 mingw32="yes"
-LIBPREF=""
-LIBSUF=".lib"
-SLIBPREF=""
-SLIBSUF=".dll"
 ;;
 CYGWIN*)
 v4l="no"
@@ -224,6 +271,7 @@ LIBPREF=""
 LIBSUF=".lib"
 SLIBPREF=""
 SLIBSUF=".dll"
+EXESUF=".exe"
 extralibs=""
 v4l="no"
 audio_oss="no"
@@ -326,6 +374,8 @@ for opt do
   ;;
   --enable-faadbin) faadbin="yes"
   ;;
+  --enable-faac) faac="yes"
+  ;;
   --disable-vhook) vhook="no"
   ;;
   --disable-simple_idct) simpleidct="no"
@@ -333,6 +383,10 @@ for opt do
   --enable-mingw32) mingw32="yes"
   ;;
   --enable-shared) lshared="yes"
+  ;;
+  --disable-debug) debug="no"
+  ;;
+  --disable-opts) optimize="no"
   ;;
   --disable-mpegaudio-hp) mpegaudio_hp="no"
   ;;
@@ -359,6 +413,29 @@ if test $mmx = "default"; then
         mmx="yes"
     else
         mmx="no"
+    fi
+fi
+
+#Darwin CC versions
+if test $targetos = Darwin; then
+    if test -n "$($cc -v 2>&1 | grep xlc)"; then
+       CFLAGS="-qpdf2 -qlanglvl=extc99 -qmaxmem=-1 -qarch=auto -qtune=auto"
+    else
+       gcc_version="$($cc -v 2>&1 | grep version | cut -d ' ' -f3-)"
+       case "$gcc_version" in
+           *2.95*)
+               CFLAGS="-no-cpp-precomp -pipe -fomit-frame-pointer"
+               ;;
+           *3.1*)
+               CFLAGS="-no-cpp-precomp -pipe -fomit-frame-pointer -force_cpusubtype_ALL -Wno-sign-compare"
+               ;;
+           *3.3*)
+               CFLAGS="-no-cpp-precomp -pipe -fomit-frame-pointer -mdynamic-no-pic -force_cpusubtype_ALL -Wno-sign-compare"
+               ;;
+           *)
+               CFLAGS="-no-cpp-precomp -pipe -fomit-frame-pointer -mdynamic-no-pic"
+               ;;
+       esac
     fi
 fi
 
@@ -397,21 +474,21 @@ if test $tune != "generic"; then
 	    TUNECPU=ppc604
 	;;
 	G3|g3|75*|ppc75*|PowerPC75*)
-	    CFLAGS="$CFLAGS -mcpu=750 -mtune=750"
+	    CFLAGS="$CFLAGS -mcpu=750 -mtune=750 -mpowerpc-gfxopt"
 	    if test $altivec = "yes"; then
 		echo "WARNING: tuning for PPC75x but altivec enabled !";
 	    fi
 	    TUNECPU=ppc750
 	;;
 	G4|g4|745*|ppc745*|PowerPC745*)
-	    CFLAGS="$CFLAGS -mcpu=7450 -mtune=7450"
+	    CFLAGS="$CFLAGS -mcpu=7450 -mtune=7450 -mpowerpc-gfxopt"
 	    if test $altivec = "no"; then
 		echo "WARNING: tuning for PPC745x but altivec disabled !";
 	    fi
 	    TUNECPU=ppc7450
 	;;
 	74*|ppc74*|PowerPC74*)
-	    CFLAGS="$CFLAGS -mcpu=7400 -mtune=7400"
+	    CFLAGS="$CFLAGS -mcpu=7400 -mtune=7400 -mpowerpc-gfxopt"
 	    if test $altivec = "no"; then
 		echo "WARNING: tuning for PPC74xx but altivec disabled !";
 	    fi
@@ -430,10 +507,10 @@ if test $tune != "generic"; then
     esac
 fi
 
-# AltiVec flags: The FSF version of GCC differs from the Darwin version 
+# AltiVec flags: The FSF version of GCC differs from the Apple version 
 if test $cpu = "powerpc"; then
     if test $altivec = "yes"; then
-        if test "$darwin" = "yes"; then
+        if test -n "$($cc -v 2>&1 | grep version | grep Apple)"; then
             CFLAGS="$CFLAGS -faltivec"
         else
             CFLAGS="$CFLAGS -maltivec -mabi=altivec"
@@ -499,8 +576,15 @@ if test "$mingw32" = "yes" ; then
     v4l="no"
     audio_oss="no"
     dv1394="no"
+    ffserver="no"
     network="no"
-    prefix="/c/Progra~1/FFmpeg"
+    LIBPREF=""
+    LIBSUF=".lib"
+    SLIBPREF=""
+    SLIBSUF=".dll"
+    EXESUF=".exe"
+    prefix="/c/Program Files/FFmpeg"
+    bindir="$prefix"
 fi
 
 cc="${cross_prefix}${cc}"
@@ -637,12 +721,12 @@ EOF
 
 ldl=-ldl
 
-if $cc -o $TMPE $TMPC -ldl 2> /dev/null  ; then
+if $cc -o $TMPE $TMPC -ldl > /dev/null 2>&1 ; then
 dlfcn=yes
 dlopen=yes
 fi
 
-if $cc -o $TMPE $TMPC 2> /dev/null  ; then
+if $cc -o $TMPE $TMPC > /dev/null 2>&1 ; then
 dlfcn=yes
 dlopen=yes
 ldl=""
@@ -652,11 +736,11 @@ cat > $TMPC << EOF
 int main( void ) { return (int) dlopen("foo", 0); }
 EOF
 
-if $cc -o $TMPE $TMPC -ldl 2> /dev/null  ; then
+if $cc -o $TMPE $TMPC -ldl > /dev/null 2>&1 ; then
 dlopen=yes
 fi
 
-if $cc -o $TMPE $TMPC 2> /dev/null  ; then
+if $cc -o $TMPE $TMPC > /dev/null 2>&1 ; then
 dlopen=yes
 ldl=""
 fi
@@ -675,7 +759,7 @@ int main( void ) { return (int) imlib_load_font("foo"); }
 EOF
 
 imlib2=no
-if $cc -o $TMPE $TMPC -lImlib2 2> /dev/null  ; then
+if $cc -o $TMPE $TMPC -lImlib2 > /dev/null 2>&1 ; then
 imlib2=yes
 fi
 
@@ -690,7 +774,7 @@ EOF
 freetype2=no
 if test "x$targetos" != "xBeOS" && test "$os2" != "yes"; then
   if test "`which freetype-config`" != ""; then
-    if $cc -o $TMPE $TMPC `freetype-config --cflags` `freetype-config --libs`  2> /dev/null ; then
+    if $cc -o $TMPE $TMPC `freetype-config --cflags` `freetype-config --libs`  > /dev/null 2>&1 ; then
       freetype2=yes
     fi
   fi
@@ -707,7 +791,7 @@ fi
 #
 #sdl_too_old=no
 #sdl=no
-#if $cc -o $TMPE `sdl-config --cflags` $TMPC `sdl-config --libs`  2> /dev/null  ; then
+#if $cc -o $TMPE `sdl-config --cflags` $TMPC `sdl-config --libs`  > /dev/null 2>&1 ; then
 #_sdlversion=`sdl-config --version | sed 's/[^0-9]//g'`
 #if test "$_sdlversion" -lt 121 ; then
 #sdl_too_old=yes
@@ -715,6 +799,14 @@ fi
 #sdl=yes
 #fi
 #fi
+
+case "$($cc -v 2>&1 | grep version)" in
+    *gcc*)
+       CFLAGS="-Wall $CFLAGS"
+       ;;
+    *)
+       ;;
+esac
 
 if test "$sdl" = "no" ; then
    ffplay=no
@@ -730,70 +822,20 @@ if test "$optimize" = "small"; then
 fi
 
 if test "$optimize" = "yes"; then
+    if test -n "$($cc -v 2>&1 | grep xlc)"; then
+       CFLAGS="$CFLAGS -O5"
+       LDFLAGS="$LDFLAGS -O5"
+    else
        CFLAGS="$CFLAGS -O3"
+    fi
+fi
+
+if test x"$bindir" = x""; then
+bindir="${prefix}/bin"
 fi
 
 if test x"$mandir" = x""; then
 mandir="${prefix}/man"
-fi
-
-if test x"$1" = x"-h" -o x"$1" = x"--help" ; then
-cat << EOF
-
-Usage: configure [options]
-Options: [defaults in brackets after descriptions]
-
-EOF
-echo "Standard options:"
-echo "  --help                   print this message"
-#echo "  --prefix=PREFIX          install in PREFIX [$prefix]"
-#echo "  --mandir=DIR             man documentation in DIR [PREFIX/man]"
-#echo "  --enable-mp3lame         enable mp3 encoding via libmp3lame [default=no]"
-#echo "  --enable-vorbis          enable vorbis support via libvorbisenc [default=no]"
-#echo "  --enable-faad            enable faad support via libfaad [default=no]"
-#echo "  --enable-faadbin         build faad support with runtime linking [default=no]"
-#echo "  --enable-win32           enable win32 cross compile"
-#echo "  --enable-mingw32         enable mingw32 native windows compile"
-#echo "  --disable-a52            disable GPL'ed A52 support [default=no]"
-#echo "  --enable-a52bin          open liba52.so.0 at runtime [default=no]"
-#echo "  --disable-pp             disable GPL'ed post processing support [default=no]"
-#echo "  --enable-shared-pp       use libpostproc.so [default=no]"
-#echo "  --enable-shared          build shared libraries [default=no]"
-#echo "  --enable-amr_nb          enable amr_nb audio codec"
-#echo "  --enable-amr_nb-fixed    use fixed point for amr-nb codec"
-#echo "  --enable-sunmlib         use Sun medialib [default=no]"
-#echo ""
-echo "Advanced options (experts only):"
-#echo "  --source-path=PATH       path of source code [$source_path]"
-#echo "  --cross-prefix=PREFIX    use PREFIX for compile tools [$cross_prefix]"
-#echo "  --cc=CC                  use C compiler CC [$cc]"
-#echo "  --make=MAKE              use specified make [$make]"
-echo "  --extra-cflags=ECFLAGS   add ECFLAGS to CFLAGS [$CFLAGS]"
-#echo "  --extra-ldflags=ELDFLAGS add ELDFLAGS to LDFLAGS [$LDFLAGS]"
-#echo "  --extra-libs=ELIBS       add ELIBS [$ELIBS]"
-#echo "  --cpu=CPU                force cpu to CPU  [$cpu]"
-#echo "  --tune=PROCESSOR         tune code for a particular CPU (may fails or misperforms on other CPUs)"
-#echo "  --powerpc-perf-enable    enable performance report on PPC (requires enabling PMC)"
-#echo "  --disable-mmx            disable mmx usage"
-#echo "  --disable-altivec        disable AltiVec usage"
-#echo "  --disable-audio-oss      disable OSS audio support [default=no]"
-#echo "  --disable-audio-beos     disable BeOS audio support [default=no]"
-#echo "  --disable-v4l            disable video4linux grabbing [default=no]"
-#echo "  --disable-dv1394         disable DV1394 grabbing [default=no]"
-#echo "  --disable-network        disable network support [default=no]"
-#echo "  --disable-zlib           disable zlib [default=no]"
-#echo "  --disable-simple_idct    disable simple IDCT routines [default=no]"
-#echo "  --disable-vhook          disable video hooking support"
-#echo "  --enable-gprof           enable profiling with gprof [$gprof]"
-#echo "  --disable-mpegaudio-hp   faster (but less accurate)"
-#echo "                           mpegaudio decoding [default=no]"
-#echo "  --disable-ffserver       disable ffserver build"
-#echo "  --disable-ffplay         disable ffplay build"
-#echo "  --disable-risky          disables patent encumbered codecs"
-#echo "  --enable-small           optimize for size instead of speed"
-#echo ""
-#echo "NOTE: The object files are build at the place where configure is launched"
-exit 1
 fi
 
 echo "Please note that these settings only deal with libavcodec, not MythTV."
@@ -838,6 +880,7 @@ fi
 #echo "Sun medialib support"  $sunmlib
 #echo "AMR-NB float support"  $amr_nb
 #echo "AMR-NB fixed support"  $amr_nb_fixed
+#echo "AMR-WB float support"  $amr_wb
 
 echo "Creating config.mak and config.h"
 
@@ -880,9 +923,6 @@ if test "$mmx" = "yes" ; then
   echo "TARGET_MMX=yes" >> config.mak
   echo "#define HAVE_MMX 1" >> $TMPH
   echo "#define __CPU__ 586" >> $TMPH
-fi
-if test "$mingw32" = "yes" ; then
-  echo "TARGET_MINGW32=yes" >> config.mak
 fi
 #if test "$builtin_vector" = "yes" ; then
 #  echo "TARGET_BUILTIN_VECTOR=yes" >> config.mak
@@ -1032,18 +1072,17 @@ if test "$faadbin" = "yes" ; then
   echo "CONFIG_FAADBIN=yes" >> config.mak
 fi
 
+if test "$faac" = "yes" ; then
+  echo "#define CONFIG_FAAC 1" >> $TMPH
+  echo "CONFIG_FAAC=yes" >> config.mak
+fi
+
 if test "$mingw32" = "yes" ; then
   echo "#define CONFIG_WIN32 1" >> $TMPH
   echo "CONFIG_WIN32=yes" >> config.mak
   echo "#ifndef __MINGW32__" >> $TMPH
   echo "#define __MINGW32__ 1" >> $TMPH
   echo "#endif" >> $TMPH
-  echo "__MINGW32__=1" >> config.mak
-fi
-
-if test "$cygwin" = "yes" ; then
-  # setup correct exesuffix
-  echo "CONFIG_WIN32=yes" >> config.mak
 fi
 
 if test "$os2" = "yes" ; then
@@ -1114,6 +1153,17 @@ if test "$source_path_used" = "yes" ; then
     done
 fi
 echo "SRC_PATH=$source_path" >> config.mak
+
+if test "$amr_wb" = "yes" ; then
+  echo "#define AMR_WB 1" >> $TMPH
+  echo "AMR_WB=yes" >> config.mak
+  echo
+  echo "AMR WB FLOAT NOTICE ! Make sure you have downloaded TS26.204"
+  echo "V5.1.0 from "
+  echo "http://www.3gpp.org/ftp/Specs/archive/26_series/26.204/26204-510.zip"
+  echo "and extracted the source to libavcodec/amrwb_float"
+  echo
+fi
 
 if test "$amr_nb" = "yes" ; then
   echo "#define AMR_NB 1" >> $TMPH
